### ISSUE TITLE
Add resource BioGRID interactions

### ISSUE THREAD

**Issue by bgyori** [bioregistry/bioregistry#101]
## Required

The following fields are required for all new entries in the Bioregistry:

### Name

BioGRID interactions

### Description

BioGRID is a database of physical and genetic interactions in Saccharomyces cerevisiae, Caenorhabditis elegans, Drosophila melanogaster, Homo sapiens, and Schizosaccharomyces pombe.

### Prefix

biogrid.interaction

### Homepage

thebiogrid.org

### Example Identifier

2649230

### Pattern

^\d+$

### Namespace Embedded in Identifier

> Replace this if the namespace appears in the identifier. Please write it out exactly as it appears in the identifier. For example, a GO identifier contains a redundant `GO:`, so write this text exactly.

### Contact Email

biogridadmin@gmail.com

### Comments

> Replace this with any free text you want to include with this resource in an additional field to the description

**Comment by cthoyt** [comment]
Added in version 0.2.6 (https://github.com/bioregistry/bioregistry/releases/tag/v0.2.6)
