### ISSUE TITLE
Add resource COG

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#103]
Sorry I'm just doing narrative here as this is a bit confusing

COG (cluster of orthologous genes)

These used to have URLs like http://www.ncbi.nlm.nih.gov/COG/new/release/cow.cgi?cog=COG0001

but looks like NCBI doesn't supprt any more?

But COG is still widely used - e.g. xreffed in KEGG.KO

We had this entry in the GO registry, we called it COG_Cluster
https://github.com/geneontology/go-site/blob/12ee49e984014795acb11e074768ed4daae8f5fd/metadata/db-xrefs.yaml#L380-L386

We also have a generic COG entry

https://github.com/geneontology/go-site/blob/12ee49e984014795acb11e074768ed4daae8f5fd/metadata/db-xrefs.yaml#L380-L386

But this is to refer to the one level functional groupings

**Comment by realmarcin** [comment]
Looks like this might be the url for COGs @ NCBI now

https://www.ncbi.nlm.nih.gov/research/cog/cog/COG0001/

**Comment by cthoyt** [comment]
@cmungall I'm not sure what the one-level functional groupings means. I'm about to make a commit that has COG, COG Pathways, and COG Categories. Not exactly sure which of those corresponds to functional groupings (though I'd guess Categories). After you let me know, I'll make the explicit mapping to the GO registry.
