### ISSUE TITLE
ena.embl broken link

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#106]
Links here are broken http://bioregistry.io/registry/ena.embl

I think this is caused by the double space:

https://www.ebi.ac.uk/ena//ena/browser/view/BN000065

this works

https://www.ebi.ac.uk/ena/browser/view/BN000065

(may as well change to https)

and for other types too e.g. projects
https://www.ebi.ac.uk/ena/browser/view/PRJEB45055

unsure if I should report these to identifiers.org or here.. but this issue track seems more active!

**Comment by bgyori** [comment]
Thanks @cmungall, it looks to me like this might be an issue on the provider (i.e., ENA) website. The URL pattern provided by identifiers.org is actually `https://www.ebi.ac.uk/ena/data/view/$1`, but it seems like the provider redirects that incorrectly to `https://www.ebi.ac.uk/ena//ena/browser/view/$1`. One solution is to add the correct resolution URL in Bioregistry to override this.
