### ISSUE TITLE
Add prefix insdc.run

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#131]
### Prefix

insdc.run

### Name

INSDC Run

### Homepage

https://www.insdc.org/

### Description

https://www.insdc.org/ is the authoritative source for INSDC. However, confusingly, they don't mention runs in this table. I think we should ask them to include.

ENA is a partner and they have documentation here:

https://ena-docs.readthedocs.io/en/latest/submit/general-guide/accessions.html

Runs | (E\|D\|S)RR[0-9]{6,} | ERR123456
-- | -- | --

### Example Identifier

insdc.run:ERR436051

### Regular Expression Pattern

^(E|D|S)RR[0-9]{6,}$

### Redundant Prefix in Regular Expression Pattern

^insdc.run:(E|D|S)RR[0-9]{6,}$

### Provider Format URL

https://www.ebi.ac.uk/ena/browser/view/$1

### Additional Comments

As for all INSDC IDs, there are 3 resolvers that should be treated as equivalent (regardless of which database the record was submitted to - the first letter of the accession)

https://www.ebi.ac.uk/ena/browser/view/ERR436051 
https://www.ncbi.nlm.nih.gov/sra/ERR436051

mgnify will also resolve these IDs but I don't think they should be treated as the primary resolver:
https://github.com/bioregistry/bioregistry/issues/109

**Comment by cthoyt** [comment]
Hi @cmungall, thanks for being the first person to try this out! There were a few things you did that were unexpected, but this itself is good feedback.

1. The description field is the stuff that will end up in the bioregistry page, and you added some stuff that should probably have gone in additional comments. That's okay, we can always update stuff!
2. The example identifier wasn't supposed to have the prefix in it, but I suppose it's no harm done and could be computationally removed
3. The "Redundant Prefix in Regular Expression Pattern" field is a bit more complicated than just saying "namespace embedded in LUI" since it includes lots of extra information about the casing and any weird variation. For this entry, it should have been left blank. I'll try and update the description on this one to make it more clear

**Comment by cthoyt** [comment]
Also it would be nice to write out the acronym INSDC since it does not say anywhere in the description what it is

**Comment by cthoyt** [comment]
I made a few updates to address these. But we still need a better description text about what a Run is

**Comment by cmungall** [comment]
I'm not sure how best to handle INSDC. 

The general strategy handed down from identifiers.org is subnamespacing, e.g.

https://bioregistry.io/registry/kegg
https://bioregistry.io/registry/kegg.orthology
https://bioregistry.io/registry/kegg.FOO

I don't love this as it means there are two possible CURIEs for any KEGG entity, e.g.

https://bioregistry.io/kegg:K00001
https://bioregistry.io/kegg.orthology:K00001

As you know I am in favor of The One True Way to write a CURIE. I might suggest that the parent be annotated in such a way that explicitly indicates that this is a collector

This was not done consistently, so for example we have

http://bioregistry.io/registry/wormpep
http://bioregistry.io/registry/wormbase

For RGD we have rgd, rgd.qtl, rgd.strain. Here the parent is more of a bucket than it is a parent. It is the prefix for all things that are not qtls or strains (again, RGD has many many datatypes, and it's not clear why qtls and strains get their own subnamespace and everything else is rolled up into the parent)

I suggest the following guidelines (v drafty)

 - most resources should consider having a single namespace and rolling up everything to that namespace. They should take care of resolving everything within that namespace
 - "bigger" entities such as NCBI, KEGG, etc could be seen as collections of distinct databases justifying subnamespacing
 - where subnamespacing does happen, we encourage the parent namespace to be a collector and for the set of subnamespaces to be JEPD jointly exhaustive and pairwise disjoint
 - metadata about the uber-database can go in the parent entity, and the UI can be smart enough to replicate some of that in pages for the subnamespaces
 - care should be taken to assign the correct "parent". E,g, if a database is NCBI-specific, then `ncbi.foo` but if it's an ID that is jointly shared across INSDC, then `insdc.foo`
 - the period is the default divider, but there may be legacy cases where this is omitted, e.g. ncbigene, ncbitaxon
 - don't squat by making your namespace a core biological category. If you have a gene database, then don't try and squat `gene` (unless this is the one true effort to unite all genes, oh that would be wonderful).
