### ISSUE TITLE
Update regular expression pattern for atcc

### ISSUE THREAD

**Issue by bgyori** [bioregistry/bioregistry#147]
### Prefix

atcc

### New Regular Expression Pattern

^([A-Z]+-)?\d+$

### Explanation

The example identifier 11303 currently listed is valid and exists but there are many other ATCC IDs like CRL-2522 that are also valid. There may be more though all the ones I've spot-checked match this new pattern.

**Comment by cthoyt** [comment]
The `+-` is funny! Right now there isn't an automated script for making a PR on this, but it looks like the issue form worked well. Thanks for pointing this out
