### ISSUE TITLE
Add prefix wwf.ecoregion

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#153]
### Prefix

wwf.ecoregion

### Name

World Wildlife Fund Ecoregion

### Homepage

https://www.worldwildlife.org/biomes

### Description

WWF ecoregions are large unit of land or water containing a geographically distinct assemblage of species, natural communities, and environmental conditions.

We include xrefs to them from ENVO https://github.com/EnvironmentOntology/envo/issues/658

Wikidata also links to them

https://www.wikidata.org/wiki/Q929975
https://www.wikidata.org/wiki/Property:P1294

### Example Identifier

AT1402

### Regular Expression Pattern

AT\\d+

### Redundant Prefix in Regular Expression Pattern

wwf.ecoregion:AT\\d+

### Provider Format URL

https://www.worldwildlife.org/ecoregions/$1

**Comment by cthoyt** [comment]
Thanks for the submission. I've made the following updates:

1. Moved parts of the description to the "comments" section
2. Manually added the wikidata fields into the structured fields (I made a new issue #155 for adding further fields to the form)
3. The redundant prefix that you added wasn't necessary - this is only for situations like GO, CHEBI, and other OBO nomenclatures where people sometimes double it up. I removed it
