### ISSUE TITLE
Add way to indicate preferred casing for identifiers

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#46]
I personally find lowercase pleasing, but many databases and ontologies have a preferred casing, and in some situations identifier resolution or matching is case sensitive

it's conventional for most ontologies to use uppercase prefixes in CURIEs and corresponding PURLs. E.g. if you write `go:0008150` then it won't match `GO:0008150` in all situations

There are some ontologies in OBO that use mixed case - e.g. FBbt. Again it is important to get the casing correct

This is distinct from a preferred acronym for humans. E.g. ChEBI refer to themselves as `ChEBI` but the canonical identifiers are all uppercase.

Similarly many databases have a preferred casing, this is usually uppercase, but there are mixed case databases, e.g. FlyBase

Can we have a way to indicate the preferred form for purposes of identifiers?

**Comment by cthoyt** [comment]
For the most part, my philosophy is that bioregistry should completely avoid casing, but be smart enough to map to the appropriate casing for any output such as OBO Foundry and OLS. If this isn't general enough, we could also track a "stylized" prefix that includes appropriate caps and perhaps additional punctuation

**Comment by cthoyt** [comment]
After looking into it more, I realized OBO Foundry has a "preferredPrefix" key that I had not taken advantage of yet. I will incorporate that ASAP

**Comment by cmungall** [comment]
yep, this is only used for an exception to the all-uppercase rule. A
non-entry means preferredPrefix is all uppercase

**Comment by cmungall** [comment]
Hmm, I see this is closed but in http://bioregistry.io/registry/fbbt

There is nothing indicating that FBbt:NNN is the canonical form

Also with e.g. http://bioregistry.io/registry/go

the canonical prefix is somewhat obscured in the regex, and it seems arbitrary which ones have the prefix in the regex?

**Comment by cthoyt** [comment]
> Hmm, I see this is closed but in http://bioregistry.io/registry/fbbt
> 
> There is nothing indicating that FBbt:NNN is the canonical form

FBbt:NNN is canonical form with respect to OBO Foundry and the Bioregistry is now generating OBO Foundry (and therefore OLS) IRIs in the way you'd expect (see https://bioregistry.io/reference/fbbt:00007294)

The metaregistry section on http://bioregistry.io/registry/fbbt shows that FBbt is the canonical form for OBO Foundry, as well as the wide variety of other forms it takes in other registries (BioPortal uses FB-BT, crazy!). If that wasn't prominent enough, we could try reorganizing the page.

> Also with e.g. http://bioregistry.io/registry/go
> 
> the canonical prefix is somewhat obscured in the regex, and it seems arbitrary which ones have the prefix in the regex?

Could you elaborate? 

Quite a few of these were imported from Identifiers.org, which aren't perfect. The bioregistry has a lot of general logic for dealing with the redundant nomenclature so some of these slipped through the cracks.

**Comment by cmungall** [comment]
This isn't just OBO Foundry, the correct way to write the ID is FBbt:NNNN,
see FlyBase for examples

yep, I realize most of this is due to how it was represented in
identifiers.org. I would take the GO registry as canonical for casing
information

**Comment by cmungall** [comment]
@cthoyt can we reopen this issue? This is pretty much a blocker to us using bioregistry

**Comment by cthoyt** [comment]
I'm not exactly sure what the blocker is - is it that the bioregistry's prefixes don't use casing information, or that there isn't a way to build OBO-style PURLs correctly? Can you give a bit more information about the use case?

**Comment by cmungall** [comment]
Not just OBO, FlyBase isn't in OBO

The correct way to write the CURIE is `FlyBase:FBgn0011293`, according to flybase themselves, the GO registry, etc. It should always have been recorded this way but identifiers.org made the decision to lowercase everything and lose the casing information.

If we don't have agreement and a standard then joins don't work without string transformations

**Comment by cthoyt** [comment]
so the solution in OBO Foundry is to have an extra field like "preferred prefix". Right now in the bioregistry, the OBO entries with this have that data a bit nested. Would an amenable solution be to duplicate that information as another top-level field?

As far as the prefixes go themselves, even though FlyBase might use a certain standard internally, I'd support that it's up to each registry (and the metaregistry) to assign and track those - I think it's only fair to say a CURIE is "correct" with respect to a given registry. Have you been able to cope with this w.r.t. identifiers.org? Or is this still an ongoing problem, too?

**Comment by cthoyt** [comment]
@cmungall maybe we should get on a short call to discuss :) I'm on the train back to my home in Germany from now so today is going to be tough with the jetlag, but anytime that's good for the west coast/central europe time later this week would work for me. I'll message you on slack
