### ISSUE TITLE
simplify obo ingest

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#49]
there is a lot going on in the obofoundry ingester, including doing checkouts of repos, checking if an obo file is there..

I think this is all uneccessary, we probably have not done a good job of advertising the right way to collect metadata from obo

**Comment by cthoyt** [comment]
I would love to see some of this metadata better organized on the OBO side :)

**Comment by cthoyt** [comment]
I updated the way OBO Foundry's registry is ingested in https://github.com/bioregistry/bioregistry/pull/80. Now it's much more slick in how it grabs the download URLs for OWL, OBO, and OBO Graph JSON. The downside is without all of this complicated checking, there's still no explicit field denoting the github/source control repository (though it could maybe be inferred from other fields like the issue tracker for a large portion)
