### ISSUE TITLE
OMIM entry

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#64]
http://bioregistry.io/registry/mim

Alternative Prefixes
OMIM OMIMPS PS

I am not sure the phenotypic series should be considered alternative prefixes. The phenotypic series and the individual disease entries are disjoint categories, and there are distinct ways to resolve them

Example of a PS:
https://omim.org/phenotypicSeries/PS214100

Depending on the registry's strategy for typing, one possibility is to introduce a ns `mim.ps`. This is consistent with decisions made by identifiers.org for other databases that have entities of different types, e.g KEGG, and these decisions are inherited by bioregistry

Also the pattern `^[*#+%^]?\d{6}$`

Seems to be confusing the file format with the ID. the `*#+%^` is not part of the ID, even if the omim.txt file and the website show these symbols preceding the ID

**Comment by cthoyt** [comment]
`mim.ps` is now live https://bioregistry.io/registry/mim.ps
