### ISSUE TITLE
Add STY (UMLS semantic types)

### ISSUE THREAD

**Issue by cmungall** [bioregistry/bioregistry#83]
For
http://purl.bioontology.org/ontology/STY

E.g.
http://purl.bioontology.org/ontology/STY/T039

bioportal also includes a rich source of prefixes, but it's not clear you would want to include them all since it may be end up de-facto squatting

**Comment by cthoyt** [comment]
The Bioregistry automatically adds all new entries from OBO Foundry, Identifiers.org, and the OLS, but not the other sources. BioPortal has much more garbage in it, so it's only automatically mapped but new entries aren't automatically included.

**Comment by cthoyt** [comment]
Please see https://bioregistry.io/registry/sty
